#!/usr/bin/env bash
# Ce script vérifie si un hôte est sur le réseau en utilisant la commande ping

if [ "$#" -ne 1 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

ping -c 5 "$1"
