#!/bin/bash
# Sauvegarder l'état actuel du fichier /etc/hosts

cp /etc/hosts /etc/hosts.backup

# Modifier l'entrée pour localhost
sudo sed -i '/127.0.0.1/s/127.0.0.1/127.0.0.2/' /etc/hosts

# Ajouter ou modifier l'entrée pour facebook.com
if grep -q "facebook.com" /etc/hosts; then
    sudo sed -i '/facebook.com/s/.*/8.8.8.8    facebook.com/' /etc/hosts
else
    echo "8.8.8.8    facebook.com" | sudo tee -a /etc/hosts
fi

echo "Les modifications ont été appliquées avec succès."
